Adds checkpoint overview
lcawl/stack-docs pull request #3
Opened 2019-07-19 19:18 UTC by lcawl

This PR adds a topic about data frame transform checkpoints in the Stack Overview.

It builds on the structural changes in https://github.com/elastic/stack-docs/pull/435

2019-07-19 19:20 UTC, lcawl commented
This content talks about "checkpoints" as a "thing", but if we prefer to talk about "checkpointing" as a process, I can revamp this text.

2019-07-19 19:24 UTC, lcawl commented
You can preview this content here: https://doc-review-63bf6.firebaseapp.com/x4/ml-transform-checkpoints.html

2019-07-22 13:33 UTC, sophiec20 requested changes
I'm not entirely convinced this content belongs as "Overview" content -- it is more like "Concepts" or "How it works" .. but it is better to be transparent and publish than to hold it up whilst we think about nav placement.

Requested some changes.

2019-07-22 13:33 UTC, sophiec20 commented on docs/en/stack/data-frames/checkpoints.asciidoc
> +the source indices based on sequence IDs. This check is done based on the
pls remove "based on sequence IDs" -- this is too specific an implementation detail and will also change.

2019-07-22 13:33 UTC, sophiec20 commented on docs/en/stack/data-frames/checkpoints.asciidoc
> +//TBD: This seems to imply it doesn't handle deletions. Do we want to clarify that?
Handling of deletions should already be in limitations. It would be too much info to add here (and also likely to change in next iteration).

2019-07-22 13:33 UTC, sophiec20 commented on docs/en/stack/data-frames/checkpoints.asciidoc
> +//TBD: It's not clear why the previous two sentences are noteworthy from a user point of view.
The fact that we are using composite aggregations and terms queries show that transforms are built on top of existing elasticsearch constructs. Performance and scalability considerations for aggs and terms queries also apply to data frame transforms, therefore worth being transparent. This is the point of a "how it works" section.

Pagination is relevant to both searching and indexing. This step does not show that paging is relevant to both. Perhaps change last sentence from `After all the changes have been applied, the checkpoint is complete.` to `After all the pages of changes have been applied, the checkpoint is complete.`

2019-07-22 13:33 UTC, sophiec20 commented on docs/en/stack/data-frames/checkpoints.asciidoc
> +{dataframe-transform} to take longer to complete quietly in the background,
pls remove "quietly in the background" ..

2019-07-22 13:33 UTC, sophiec20 commented on docs/en/stack/data-frames/checkpoints.asciidoc
> +For example, a {cdataframe-transform}:
These are not really "examples" .. these are steps performed during checkpointing.

2019-07-22 18:00 UTC, merged